### ISSUE TITLE
Can't watch any episode after switching to DE / DE from EN / US

### ISSUE THREAD

**Issue by MartinX3** [wargio/plugin.video.southpark_unofficial#15] opened 2019-08-14 20:19 UTC
```
2019-08-14 22:10:40.240 T:139678878402304  NOTICE: ADDON: xbmc.addon v18.3.0 installed
2019-08-14 22:10:40.240 T:139678878402304  NOTICE: ADDON: xbmc.core v0.1.0 installed
2019-08-14 22:10:40.240 T:139678878402304  NOTICE: ADDON: xbmc.gui v5.14.0 installed
2019-08-14 22:10:40.240 T:139678878402304  NOTICE: ADDON: xbmc.json v10.3.0 installed
2019-08-14 22:10:40.240 T:139678878402304  NOTICE: ADDON: xbmc.metadata v2.1.0 installed
2019-08-14 22:10:40.240 T:139678878402304  NOTICE: ADDON: xbmc.python v2.26.0 installed
2019-08-14 22:10:40.240 T:139678878402304  NOTICE: ADDON: xbmc.webinterface v1.0.0 installed
2019-08-14 22:10:50.613 T:139680180586624 WARNING: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2019-08-14 22:10:51.850 T:139680180586624   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-08-14 22:10:56.306 T:139678611126016   ERROR: EXCEPTION: Unknown exception thrown from the call "XBMCAddon::xbmcplugin::setResolvedUrl"
2019-08-14 22:10:56.307 T:139678611126016   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown exception thrown from the call "XBMCAddon::xbmcplugin::setResolvedUrl"
                                            Traceback (most recent call last):
                                              File "/home/martin/.kodi/addons/plugin.video.southpark_unofficial/default.py", line 9, in <module>
                                                plugin.handle()
                                              File "/home/martin/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 584, in handle
                                                self.play_episode(kodi.PARAM_URL, kodi.PARAM_EP_TITLE, kodi.PARAM_EP_THUMBNAIL)
                                              File "/home/martin/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 443, in play_episode
                                                xbmcplugin.setResolvedUrl(handle=self.phandle, succeeded=True, listitem=start_listitem)
                                            RuntimeError: Unknown exception thrown from the call "XBMCAddon::xbmcplugin::setResolvedUrl"
                                            -->End of Python script error report<--
2019-08-14 22:10:56.345 T:139680180586624   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.southpark_unofficial/?url=bfe08b83-ac19-11e8-b956-70df2f866ace&mode=sp:play&title=Nobody Got Cereal?&thumbnail=https://southparkstudios.mtvnimages.com/images/shows/south-park/episode-thumbnails/season-22/south-park-s22e07-Nobody-Got-Cereal_16x9_2.jpg]
2019-08-14 22:10:56.345 T:139680180586624 WARNING: Attempt to set unplayable index 0
```

**Comment by wargio** [comment] 2019-08-15 09:16
Hi, thanks for reporting the big, are you using the latest version?

**Comment by MartinX3** [comment] 2019-08-15 09:24
Of course (0.5.1) :)
Always updating my addons and the kodi version itself to the stable branch.

Seems to happen with the newest addon updates which came in the last time.

**Comment by wargio** [comment] 2019-08-16 08:10
no, no need. i'll check, maybe something changed in the german SP

**Comment by wargio** [comment] 2019-08-16 13:43
ok, so i tested and looks an issue only on season 22 of the german server. i'll try to fix it asap

**Comment by wargio** [comment] 2019-08-17 14:25
looks like only a few streams of the 22nd seasons are impacted but i do not understand why.

**Comment by MartinX3** [comment] 2019-08-17 14:50
Means the code needs to get debugged by many print() statements to look what's different and need to adapted?

**Comment by wargio** [comment] 2019-08-19 08:10
nono. it means that the issue is the resource linked to, is not available even if the link is correct.

**Comment by MartinX3** [comment] 2019-08-19 13:14
Sad to hear and thank you for the info :(

**Comment by wargio** [comment] 2019-08-19 13:21
i'll try anyway to fix the issue.

**Comment by wargio** [comment] 2019-09-30 12:38
Fixed with https://github.com/wargio/plugin.video.southpark_unofficial/commit/f383c5027f9c086dbadf8bcc6a204c1b55286c57

Waiting to be merged here: https://github.com/xbmc/repo-plugins/pull/2537

**Closed by wargio** 2019-09-30 12:38 UTC
