### ISSUE TITLE
New apis everything is broken.

### ISSUE THREAD

**Issue by Matheos96** [wargio/plugin.video.southpark_unofficial#26] opened 2020-09-24 21:04 UTC
This suddenly started happening today:

> 2020-09-24 23:42:54.168 T:2288956272   ERROR: GetDirectory - Error getting plugin://plugin.video.southpark_unofficial/?mode=sp%3aseason&url=18
> 2020-09-24 23:42:54.178 T:3011183200   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.southpark_unofficial/?mode=sp%3aseason&url=18) failed
> 2020-09-24 23:42:54.479 T:2314134384 WARNING: Attempt to use invalid handle 5
> 2020-09-24 23:43:01.224 T:2314134384   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <class 'urllib2.HTTPError'>
>                                             Error Contents: HTTP Error 404: Not Found
>                                             Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/plugin.video.southpark_unofficial/default.py", line 9, in <module>
>                                                 plugin.handle()
>                                               File "/storage/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 646, in handle
>                                                 self.create_episodes(kodi.PARAM_URL)
>                                               File "/storage/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 434, in create_episodes
>                                                 jsonrsp = _http_get(self.helper.season_data(season))
>                                               File "/storage/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 102, in _http_get
>                                                 response = urlopen(req)
>                                               File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>                                               File "/usr/lib/python2.7/urllib2.py", line 435, in open
>                                               File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>                                               File "/usr/lib/python2.7/urllib2.py", line 467, in error
>                                               File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>                                               File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
>                                               File "/usr/lib/python2.7/urllib2.py", line 435, in open
>                                               File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>                                               File "/usr/lib/python2.7/urllib2.py", line 473, in error
>                                               File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>                                               File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
>                                             HTTPError: HTTP Error 404: Not Found
>                                             -->End of Python script error report<--

Worked flawlessy until today. Maybe southparkstudios.nu changed something?

**Comment by jjok** [comment] 2020-09-24 22:02
I'm seeing this same error. I just installed today for the first time though, so I can't say if it was working previously.

**Comment by wargio** [comment] 2020-09-25 10:07
it's quite possible.

**Comment by Matheos96** [comment] 2020-09-25 14:48
> it's quite possible. i'll fix it asap.

Thanks man :D

**Comment by wargio** [comment] 2020-09-25 14:56
ok, they have completely changed the apis in all the sp websites.

**Comment by Matheos96** [comment] 2020-09-25 15:00
> ok, they have completely changed the apis in all the sp websites.

I was afraid so... :( Hope u can figure it out. Hit me up if there is anything I can do to help. I don't know kodi plugins well but I know python and web development nd shit quite well. Master's student in Computer Engineering :)

**Comment by wargio** [comment] 2020-09-25 15:56
no, i already figured out an easy way to use the new website.

**Comment by Matheos96** [comment] 2020-09-25 16:06
> no, i already figured out an easy way to use the new website.

Ok, awsm! :) Waiting patiently for the update

**Comment by MrsZizzy11** [comment] 2020-09-26 02:47
Waiting patiently as well.  Thanks!

**Comment by floreno** [comment] 2020-09-28 05:10
Just startet watching two weeks ago. Waiting patiently as well for the update.
@wargio Thank you for ur work in advanced.

**Comment by SerpentDrago** [comment] 2020-09-29 13:14
Can confirm this is broken . 

Request , when you do get around to fixing it (thanks by the way ) could you be sure to release on this github a version without python3 as a dep . as that will prevent it working in kodi 18 .  or is that what the py2 branch is for ? 

Thanks

**Comment by wargio** [comment] 2020-09-29 14:05
> Can confirm this is broken .
> 
> Request , when you do get around to fixing it (thanks by the way ) could you be sure to release on this github a version without python3 as a dep . as that will prevent it working in kodi 18 . or is that what the py2 branch is for ?
> 
> Thanks

Just use the official repo version.

**Comment by SerpentDrago** [comment] 2020-09-30 00:06
Ok was not sure if you were the official maintainer of that and pushing to the official kodi repo . Was out looking for a fix and who was working on it

**Comment by wargio** [comment] 2020-09-30 11:38
Between today and tomorrow the 0.6.0 helix and matrix versions should be pushed to the main repo.

Right now i can't support Spanish, German and Swedish.

The issue is because the new apis are kinda broken on the non US websites. the behaviour is different and the returned data is kinda weird. I'll wait a week before adding those back again. Sorry for this :(

**Comment by wargio** [comment] 2020-09-30 11:44
i'm closing this and move this to new issue.

**Closed by wargio** 2020-09-30 11:44 UTC
Labels: enhancement

**Comment by beachmiles** [comment] 2020-10-03 08:10
The 0.6.0 version is still not working here in the US, looks like its trying to access /tmp/test.html which isn't accessible. Here is the kodi log.
2020-10-03 00:57:22.199 T:16954   ERROR: [sp.addon] [Errno 2] No such file or directory: '/tmp/test.html'
2020-10-03 00:57:22.226 T:16954   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.southpark_unofficial/default.py", line 8, in <module>
                                                plugin = southpark.SouthParkAddon(argv=sys.argv)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 423, in __init__
                                                self.data      = _load_data(self.options.audio(), self.paths.PLUGIN_DATA)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 392, in _load_data
                                                return SP_Data(addon_data["seasons"], addon_data["created"])
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
2020-10-03 00:57:22.249 T:16953   ERROR: GetDirectory - Error getting plugin://plugin.video.southpark_unofficial/
2020-10-03 00:57:22.256 T:16694   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.southpark_unofficial/) failed
2020-10-03 00:59:15.452 T:16694   ERROR: Control 55 in window 10025 has been asked to focus, but it can't

**Comment by wargio** [comment] 2020-10-03 12:25
god damn. i left some debug stuff? i think that is only android related.

**Comment by Matheos96** [comment] 2020-10-03 12:29
The update never became available on my Libreelec install so I cloned the python2 branch and installed it manually. Seasons were loaded fine and so were episodes, but nothing would play. I am on the road atm so don't have a log unfortunately. But there were no python errors at least...

**Comment by wargio** [comment] 2020-10-03 12:33
the issue is related to non *nix systems. i already pushed a 0.6.1 on the official repo.
@Matheos96 you need HLS to be able to watch the episodes.

**Comment by Matheos96** [comment] 2020-10-03 12:36
LibreELEC doesn't have HLS? Also could you ellaborate. Is there some library I could install in order to get it working? I assume this change is due to the new api?

**Comment by wargio** [comment] 2020-10-03 12:42
I do not know. depends how they build kodi and with which support. unfortunately with the new apis, things are slightly different. before it was 3 streams. now it is one unique stream.
Things are kinda weird because even if the website looks the same on all the regions, the data is different.
Also the behavior of their webpages is weird.
for example on the american one i can find all the links in the page json, but on the german one is embedded in the HTML itself and on the swedish one the seasons are sometimes there and sometimes not there.

**Comment by wargio** [comment] 2020-10-03 12:45
0.6.1+matrix has been merged. within 24 hours the 0.6.1 pre matrix will also be merged.

**Comment by Matheos96** [comment] 2020-10-03 13:21
> I do not know. depends how they build kodi and with which support. unfortunately with the new apis, things are slightly different. before it was 3 streams. now it is one unique stream.
> Things are kinda weird because even if the website looks the same on all the regions, the data is different.
> Also the behavior of their webpages is weird.
> for example on the american one i can find all the links in the page json, but on the german one is embedded in the HTML itself and on the swedish one the seasons are sometimes there and sometimes not there.

Yea. I looked into the streams myself earlier. On the SWE there are three streams per ep but each new stream is only loaded (.m3u) when the previous stream has finished or u fastforwarded past it. 

Seems a bit messy. Maybe they still standardizing it (I hope)... Hope u guys find a solution for all possible cases, but hella annoying if the apis and behind the scenes stuff differs between versions. So stupid

**Comment by Jool-Pi** [comment] 2020-10-12 16:25
Dear Wargio,

I did clean installation of Kodi (18,8 Liberelec) on Pi3 and installed your add on straight from kodi repo - its 0.6.2 by deroad (is that yours?)
when I try play any video its just does not play. it has the  loading episode message then loading turning circle pop up but then nothing happens. no message of error (I didnt yet copy the log)
I tried changing location but nothing helped. 
Is anyone else experience this issue?

**Comment by eldergabriel** [comment] 2020-10-13 06:04
> Dear Wargio,
> 
> I did clean installation of Kodi (18,8 Liberelec) on Pi3 and installed your add on straight from kodi repo - its 0.6.2 by deroad (is that yours?)
> when I try play any video its just does not play. it has the loading episode message then loading turning circle pop up but then nothing happens. no message of error (I didnt yet copy the log)
> I tried changing location but nothing helped.
> Is anyone else experience this issue?

@Jool-Pi,

I have the same problem on my pi2 (model b, I think) with kodi on osmc. It's not a fresh install like yours, but it is fully updated.

The developer has marked this issue thread as closed, so I don't know what kind of response you can expect.

I'm pretty sure that we're both running into the HLS support problem mentioned in the (currently) open issue here:
[https://github.com/wargio/plugin.video.southpark_unofficial/issues/27]

If you check your log file, I strongly suspect that you will also see the "WARNING: OpenStream - Unsupported stream 1001. Stream disabled." message in there at the time you tried to play the chosen episode, as mentioned in the aforementioned issue thread. I plan to either open a new issue on this, or pursue troubleshooting this via that thread.

**Comment by Jool-Pi** [comment] 2020-10-13 07:00
> > Dear Wargio,
> > I did clean installation of Kodi (18,8 Liberelec) on Pi3 and installed your add on straight from kodi repo - its 0.6.2 by deroad (is that yours?)
> > when I try play any video its just does not play. it has the loading episode message then loading turning circle pop up but then nothing happens. no message of error (I didnt yet copy the log)
> > I tried changing location but nothing helped.
> > Is anyone else experience this issue?
> 
> @Jool-Pi,
> 
> I have the same problem on my pi2 (model b, I think) with kodi on osmc. It's not a fresh install like yours, but it is fully updated.
> 
> The developer has marked this issue thread as closed, so I don't know what kind of response you can expect.
> 
> I'm pretty sure that we're both running into the HLS support problem mentioned in the (currently) open issue here:
> [https://github.com/wargio/plugin.video.southpark_unofficial/issues/27](url)
> 
> If you check your log file, I strongly suspect that you will also see the "WARNING: OpenStream - Unsupported stream 1001. Stream disabled." message in there at the time you tried to play the chosen episode, as mentioned in the aforementioned issue thread. I plan to either open a new issue on this, or pursue troubleshooting this via that thread.

thanks you for letting me know. I will follow the issue 27
