### ISSUE TITLE
Plugin only plays first part (of 3) not the whole episode

### ISSUE THREAD

**Issue by Blub86** [wargio/plugin.video.southpark_unofficial#13] opened 2019-02-14 07:47 UTC
Since a few days the plugin plays only the first part of every episode (southpark.de, did not test southpark.com) 

hgp9102 from forum.kodi.tv described the problem nicely:

https://forum.kodi.tv/showthread.php?tid=224662&pid=2819106#pid2819106

> I have trouble that an episode starts, but the stream length are only a couple of minutes not the whole episode... I think I found out that the home page of "South Park" changed and they promote on the default page only an intro of the real episode. If you change the page to "full episode" (german: "http://www.southpark.de/alle-episoden") then I can see the full episode with the breaks in between... The plugin refers only to the "Clips"...

**Comment by wargio** [comment] 2019-02-14 08:56
ok, thank you for reporting that. so the issue is only for the german language. i'll test today

**Comment by wargio** [comment] 2019-02-14 10:10
can you tell me which episode does that? i cannot reproduce

**Comment by Blub86** [comment] 2019-02-14 13:15
I´m watching season 14 right now, watched Episode 11, 12 and 13 (coon episodes) yesterday and those are definitely affected, but it also happened on episodes before.

**Comment by wargio** [comment] 2019-02-14 15:54
i don't have that issue.
i pushed version 0.5.0 (and soon will be merged in the kodi repo), can you try it?

**Comment by Blub86** [comment] 2019-02-15 08:51
Hello, I did some testing and tried a few episodes. I´m using Yatse on my Android device as a remote. The problem only appears when I use the South Park add-on from within the Yatse app. If I select and play episodes from within Kodi it plays the whole episode. Sorry that I didn’t found out earlier.

**Comment by wargio** [comment] 2019-02-15 09:06
Use Kore.

**Closed by wargio** 2019-02-15 09:06 UTC
Labels: wontfix
